runtime: python39

env_variables:
  UTR_EMAIL: "zachdodson12@gmail.com"
  UTR_PASSWORD: "Thailand@123"
  GOOGLE_CLOUD_PROJECT: "tennis-utr-scraper"
  MAX_PROCESSES: "16"
  TEST_SINGLE_PLAYER: "true"

automatic_scaling:
  min_instances: 0
  max_instances: 1

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

handlers:
- url: /.*
  script: auto
  secure: always